-- Create the posts table
create table public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  image_url text,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.posts enable row level security;

-- Create a policy that allows anyone to read posts
create policy "Public posts are viewable by everyone"
  on public.posts for select
  using ( true );

-- Create a policy that allows only authenticated users to insert/update/delete
create policy "Authenticated users can modify posts"
  on public.posts for all
  using ( auth.role() = 'authenticated' );
